project_id = "cyazgtnjtnyxscfzsasp"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false

[functions.submit-access-request]
verify_jwt = false
